project_id = "faxbjbbwniypaffevbuo"

[functions]
  [functions.approve-trip]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.firecrawl-search]
    verify_jwt = false
  [functions.ghl-webhook]
    verify_jwt = false
  [functions.notify-admin-signup]
    verify_jwt = false
  [functions.notify-agent-approval]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
