project_id = "faxbjbbwniypaffevbuo"

[functions.firecrawl-search]
verify_jwt = false

[functions.ghl-webhook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.notify-admin-signup]
verify_jwt = false
